# Generated by Django 4.1 on 2022-08-25 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="note",
            name="tag",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="note",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 8, 25, 2, 15, 29, 539060)
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
